name: First CI/CD

on:
    push:
        branches:
            - master

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            #step1
            - name: Set up python
              uses: actions/setup-python@v2
              with:
                python-version: 3.9
            - name: Install virtual ENV
              run: pip3 install virtualenv

            - name: virtual ENV
              uses: actions/cache@v2
              id: cache-venv
              with:
                path: venv
                key: ${{runner.os}}-venv-${{ hashFiles('**/requirements*.txt')}}
                restore-keys: |
                  ${{ runner.os }}-venv-
            

            - name: Activate virtual environment
              run: python -m venv venv && source venv/bin/activate && pip3 install -r requirements.txt
              if: steps.cache-venv.outputs.cache-hit != 'true'

            - name: Run tests
              run: . venv/bin/activate && pytest

            - name: Create archive of dependencies
              run: |
                cd ./venv/lib/python3.9/site-packages
                zip -r9 ../../../../api.zip .

            - name: Add API files to Zip file
              run: cd ./api && zip -g ../api.zip -r .

            - name: Upload zip artifacts
              uses: actions/upload-artifact@v2
              with:
                name: api_files
                path: api.zip
         
    CD:
        runs-on: ubuntu-latest
        needs: [CI]
        if: github.ref == 'ref/heads/master' && github.event_name == 'push'
        steps:
            - name: Install AWS CLI
              uses: unfor19/install-aws-cli-action@v1
              with:
                version: 1
              env:
                AWS_ACCESS_KEY_ID: ${{secrets.AWS_SECRET_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

            - name: Download Lambda api.zip
              uses: actions/download-artifact@v2
              with:
                name: api
            - name: Upload to S3
              run: aws s3 cp api.zip s3://aws-dev-pseg-lipa/input_data/api.zip
              env:
                AWS_ACCESS_KEY_ID: ${{secrets.AWS_SECRET_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
            - name: Deploy new Lambda
              run: aws lambda update-function-code --function-name fast-api-function --s3-bucket aws-dev-pseg-lipa --s3-key input_data/api.zip
              env:
                AWS_ACCESS_KEY_ID: ${{secrets.AWS_SECRET_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}